### PR TITLE
[BH-1454] Remove binary dependencies from linux build

### PR DESCRIPTION
**Pull request by paweljonskim**
Remove binary dependencies from linux build

### CODE REVIEW

**Review by mjan-dev — APPROVED** [review]

**Comment by GravisZro** [comment]
Can you also remove the binary requirement when building _just_ the unit tests?

**Comment by GravisZro** [comment]
This closes #3717

**Comment by paweljonskim** [comment]
@GravisZro 
> Can you also remove the binary requirement when building _just_ the unit tests for rt1051 and linux?

1. UT are buildable only for linux - its not possible to build UT to run on hw.
2. I believe binaries are not required to run UT on linux anymore. Do you still have problems building&running UT on linux on this branch?

**Comment by GravisZro** [comment]
1. Seems odd to me to not have the unit tests run for the target because of endian and other CPU dependent issues may arise but OK.
2. Yes, the unit tests build with this branch.

**Comment by paweljonskim** [comment]
Both PRs you mentioned failed because of wrong commit messages, not UTs fails.
> "Fix permissions issues with scripts", should match format "^(\[(EGD|BH|CP|MOS)-\d+\])+ [A-Z].+[^.]$"
Please make sure all pushed commits match the format. of others commits on master

**Review by SP2FET — APPROVED** [review]
Both Pure and Bell targets build successfully without proprietary assets access

**Pull request merged**
