### PR TITLE
[BH-1390] Popup stack added

### PR DESCRIPTION
**Pull request by tomaszrybarski-digica**
Added cherry-picked commits of popup stack

### CODE REVIEW

**Comment by pholat** [comment]
this is one of bigger changes on master, maybe just merge master from when the changes were fully integrated and add your changes on top?

**Comment by swichu91** [comment]
> this is one of bigger changes on master, maybe just merge master from when the changes were fully integrated and add your changes on top?
The idea behind this PR was to ease the process of merging stable to master. This way, we could at least test fix merge conflicts early and any issues on Bell that would rise after. Sadly, I'm not sure if this is the correct route anymore. Merging this PR with BH-140 and, at the same time, making sure the system would still work could be just too much to handle as they both target similar areas.

**Review by mjan-dev — COMMENTED** [review]
@swichu91 
Could you please fix the issue linked? It seems not to be the correct one.

**Comment by pholat** [comment]
is it still required? I ask as there is ongoing merge for stable <-> master in progress

**Comment by swichu91** [comment]
> is it still required? I ask as there is ongoing merge for stable <-> master in progress

Nope, let's remove it.

**Pull request closed without merging**
