### PR TITLE
[MOS-650] Fix spelling mistakes in README

### PR DESCRIPTION
**Pull request by jakutis**
**Description**

Just fixing two spelling mistakes in the README file.

**Your checklist for this pull request**

Make sure that this PR:
- [x] Complies with our guidelines for contributions
- [x] Has unit tests if possible.
- [x] Has documentation updated

### CODE REVIEW

**Review by SP2FET — APPROVED** [review]

**Review by kkleczkowski — APPROVED** [review]

**Comment by SP2FET** [comment]
Hi, thanks for taking the time to create a PR!
Here you have the Jira ID required to pass commit checks:
MOS-650
Rewrite the commit message and we'll try to merge it ;)

**Comment by jakutis** [comment]
Okey, rewrote the commit message

**Comment by Lefucjusz** [comment]
@jakutis Your commit doesn't have a description, which is why commit message check fails. Please add the description so it can be merged, the guidelines for contributions are written down [here](https://github.com/mudita/MuditaOS/blob/master/doc/development_workflow.md).

**Comment by jakutis** [comment]
@Lefucjusz thanks, added the description.

**Comment by SP2FET** [comment]
Hi, please do the `update with rebase` instead of `update with merge` as this creates an unnecessary commit. You can fix this out by executing `git rebase origin/master -i` and doing `fixup` on that commit, then force-pushing to the origin. 
https://fle.github.io/git-tip-keep-your-branch-clean-with-fixup-and-autosquash.html for reference ;)

I'm enabling auto-merge, so it will merge automatically when you'll get rid of this one commit ;)

**Comment by jakutis** [comment]
@SP2FET okey

**Pull request merged**
