### PR TITLE
MOS-641_read-active-sim-cardss-data-earlier-but-ask-for-unlocking-later-1

### PR DESCRIPTION
**Pull request by marziel**
Make sure that this PR:
- [x] Complies with our guidelines for contributions

### CODE REVIEW

**Review by dawidwojtas-mudita — APPROVED** [review]

**Comment by SP2FET** [comment]
Is this PR doing anything else than a rename? Maybe you missed to commit some more changes?

**Comment by marziel** [comment]
> Is this PR doing anything else than a rename? Maybe you missed to commit some more changes?

For now, it isn't yet. When analysing the code, I found out that this name was confusing me, hence the renaming.

**Comment by SP2FET** [comment]
> > Is this PR doing anything else than a rename? Maybe you missed to commit some more changes?
> 
> For now, it isn't yet. When analysing the code, I found out that this name was confusing me, hence the renaming.

So please either:
- rename the title of the PR
- wait with PR until any more changes appear

Or just turn it into a draft, as this PR doesn't seem to fix the MOS-641 issue

**Comment by marziel** [comment]
Well, it looks like we ran into a following problem: there's a low hanging fruit to improve the code, even if slightly, and the changes would be related as kind of preparation work to some bigger changes. But, it's impossible to incorporate them into _master_ without:
a) merging alongside some bigger (related) changes,
b) creating a de facto dummy, new Jira ticket just to this purpose.
I thunk this should be somhow addressed.

**Comment by marziel** [comment]
(ditto)

**Comment by SP2FET** [comment]
> Well, it looks like we ran into a following problem: there's a low hanging fruit to improve the code, even if slightly, and the changes would be related as kind of preparation work to some bigger changes. But, it's impossible to incorporate them into _master_ without: a) merging alongside some bigger (related) changes, b) creating a de facto dummy, new Jira ticket just for this purpose. I think this should be somehow addressed.

That's why I suggested turning it into draft - you can continue your work then. If you wanted to do the rename, If I were you, I'd create a subtask in Jira and then create a PR under this subtask's ID - this way we have clean history of which commit fixed which ticket

**Comment by marziel** [comment]
OK, I didn't know we allow creating PRs for subtasks - there are various policies "in the world" regarding this. So, this way seems reasonable to me.

**Pull request closed without merging**
